lifting-bits/sleigh

CMakeLists.txt
tools/sleigh-lift/CMakeLists.txt

This is useful if this project is included as a subdirectory in another project

Add CMake ALIAS for libraries and executables to mimic find_package

---

.github/workflows/main.yml
CMakeLists.txt
cmake/options.cmake
cmake/packaging.cmake
tests/find_package/src/main.cpp
tools/sleigh-lift/CMakeLists.txt
tools/sleigh-lift/src/main.cpp

Fix the include directories and allow someone to use this project with CMake's `add_subdirectory` or with FetchContent.
**Below text was original description and fixed in https://github.com/lifting-bits/sleigh/pull/17/commits/809056a33779454681a0b7da62592b29d8fcae96**
The `sleigh/` prefix would be nice to use, but I believe it's impossible for source code to support different include-directory structures in the build and install interfaces.
This issue happens when you want to support including this project using both CMake's `add_subdirectory` and `find_package`.
Maybe I'm missing something though.

Fix include directory when project is added as subdirectory

---

.github/workflows/main.yml

This uses 'restore-keys' so that we can update if the source code
changes
Also adds some ccache settings useful for GH Actions
I set the ccache max size to 400MB because eventually we'll want Windows, which means we'll have 12 total matrix jobs and 400x12=4,800 which is close enough to the max 5GB cache size per repo.
Use CMake script mode for better cross-platform support, which will also be useful when we add Windows support in #6

Fix GH Actions ccache usage

---

CMakeLists.txt

I accidentally broke documentation building during the FetchContent
commit.
This commit simplifies building documentation by _always_ rebuilding
with Doxygen during installations and only having a manual target when
not installing: `sleigh_documentation` (which also always rebuilds the
documentation)

Fix building documentation

---

scripts/update_ghidra_head.py
src/setup-ghidra-source.cmake

Makes changes to relevant CMake files to more easily automate updates to latest Ghidra commits.
Playing with integration into CI on another branch https://github.com/lifting-bits/sleigh/tree/cron-ghidra-update-head
If you run the script without any arguments, it will automatically pull down the Ghidra repo into a temporary directory, read some info, make the relevant changes, and then cleanup.
Addresses some of #18

Script to update Ghidra HEAD changes

---

.github/workflows/update_head.yml
scripts/update_ghidra_head.py

Runs the updater once a week or manually.
Requires a GitHub App to provide keys that will allow further GitHub
Actions to run on the newly create pull request. (Already added)
This PR doesn't have any effect until it's merged
Automatic creation of PRs and running of GitHub Actions is based on this documentation https://github.com/peter-evans/create-pull-request/blob/28fa4848947e0faa7fa50647691d01477589d5e9/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
See an example of an automated PR here https://github.com/ekilmer/sleigh/pull/4
closes #18

Integrate Ghidra update script into CI cron job

---

CMakeLists.txt

This target doesn't actually build or do anything---it just helps IDEs
identify all source files.
For instance, CLion highlights source files differently depending on
whether or not they are explicitly listed as a source file in the
CMakeLists.txt. This can also help identify whether the header file you
navigated to was a copied one (in the build directory to support the
include <sleigh/*> prefix) or the real one under source control.
See the `SOURCES` documentation on this page for more info https://cmake.org/cmake/help/latest/command/add_custom_target.html?highlight=add_custom_target

Add source-only custom target for header files

---

CMakeLists.txt
README.md
cmake/options.cmake

This PR makes documentation optional, even when the install target is enabled.

Make documentation actually optional

---

CMakeLists.txt
README.md
cmake/options.cmake
tools/sleigh-lift/CMakeLists.txt

Create installation rules by default.
Is there a reason I'm missing why we need a project-specific variable to control this?

Remove SLEIGH_ENABLE_INSTALL and use CMake variable

---

CMakeLists.txt
cmake/install-config.cmake
cmake/install-config.cmake.in
cmake/packaging.cmake

Let's users know where the currently installed set of specfiles are
located. This path shouldn't be compiled into any binaries that you want
to distribute in a relocatable manner because the path probably won't
exist on another computer.

Expose specfile directory in installed sleighConfig

---

CMakeLists.txt
cmake/git_watcher.cmake
include/libsleigh.hh
support/CMakeLists.txt
support/GhidraVersion.cpp.in
support/Version.cpp.in
support/Version.h
tools/sleigh-lift/src/main.cpp

Closes #42
Here's what it looks like on my machine:
```
$ sleigh-lift --version
sleigh-lift 10.1
GHIDRA Version: 10.1
GHIDRA Commit Hash: 2fcf0d21bf360af68dd87e5d8ed270ea1e72554c
Commit Hash: 586afc3ca8a06a5c4ca8adabf94eb441766080d2
Commit Date: 2022-01-31 14:49:05 +1100
Last commit by: Alex Cameron [asc@tetsuo.sh]
Commit Subject: [cmake: Cleanup]
Uncommitted changes were present during build.
```

sleigh-lift: Add a `--version` argument

---

.github/workflows/main.yml
CMakeLists.txt
README.md
cmake/install-config.cmake.in
cmake/options.cmake
cmake/packaging.cmake
src/README.md
src/setup-ghidra-source.cmake
support/GhidraVersion.cpp.in
support/SpecFilePaths.h.in

While there isn't an official convention, internally CMake uses the case
of the project name in auto-generated variables for the project, like
`<ProjectName>_BINARY_DIR` and `<ProjectName>_DIR`. We should
follow that convention.
closes #50

Consistent CMake project variable names - project name case

---

.github/workflows/main.yml
CMakeLists.txt
cmake/modules/sleighCompile.cmake

This allows user to specify an arbitrary sleigh compiler. Almost always
it's going to be the sleigh::sleigh_opt target, but in the case of
cross-compiling, that won't work because the host won't be able to run
it.
This should enable fixing https://github.com/trailofbits/maat/pull/64. Will wait until it's confirmed that this fixes that issue before merging.
This change is also backwards-incompatible with existing code that uses the function, so it will deserve a (package) version bump.

Let user specify path to sleigh compiler in CMake module

---

.github/workflows/main.yml
CMakeLists.txt
cmake/options.cmake
include/libsleigh.hh
tests/find_package/CMakeLists.txt
tools/sleigh-lift/CMakeLists.txt
tools/sleigh-lift/src/main.cpp

~Not sure why building with Debug build type fails on Windows.~ Remove compiler warnings as errors
Not sure why tests are failing on Windows also (#92).
After further consideration, I plan to merge this PR even with failing Windows tests. I will open an issue to keep track of it (#92).
I've set some `Required` GitHub Actions tests to pass before merging PRs in the repo's settings, and this excludes the Windows builds, but we should try to remember to check the Windows runs to make sure that at least the build step passes.
closes #6

Windows support

---

cmake/options.cmake
src/setup-ghidra-source.cmake

Avoid generating a `"FALSE"` in the auto-generated cmake, which would make rebuilds fail.

Fix SLEIGH rebuilds

---

patches/HEAD/0004-Fix-UBSAN-errors-in-decompiler.patch
patches/stable/0003-Fix-UBSAN-errors-in-decompiler.patch
src/setup-ghidra-source.cmake

I'm in the middle of debugging the `datatest` failures on Windows and noticed that these tests hit UB too. I figure it'd be a good idea to apply https://github.com/NationalSecurityAgency/ghidra/pull/3967 since this could be a source of platform specific nasal demons.
I'm not that hopeful that this will help this specific issue but I think it's a good patch to have regardless while we're waiting for it to get merged.

Add UBSAN decompiler fixes to patches

---

support/SpecFilePaths.h.in
support/Support.cpp

Allows FindSpecFile to succeed if the specfiles are still in the install prefix defined in CMake.

Add kSleighFullSpecInstallDir to gDefaultSearchPaths

---

src/setup-ghidra-source.cmake

When using sleigh as a dependency it fails in the GitHub Actions pipeline with an error like this:
```
HEAD is now at 9c724c1a Merge remote-tracking branch 'origin/GP-2355_AARCH64_thunk_pattern' into patch
[2/9] Performing update step for 'ghidrasource-populate'
[3/9] Performing patch step for 'ghidrasource-populate'
Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <runner@xxx>) not allowed
FAILED: ghidrasource-populate-prefix/src/ghidrasource-populate-stamp/ghidrasource-populate-patch
```
For now I just set it the same as in …

Set the git identity before patching

---

src/patches/HEAD/0001-Small-improvements-to-C-decompiler-testing-from-CLI.patch
src/patches/HEAD/0002-Add-include-guards-to-decompiler-C-headers.patch
src/patches/HEAD/0003-Fix-UBSAN-errors-in-decompiler.patch
src/patches/HEAD/0004-Use-stroull-instead-of-stroul-to-parse-address-offse.patch
src/patches/HEAD/0005-Remove-using-namespace-std-from-headers.patch
src/patches/stable/0001-Small-improvements-to-C-decompiler-testing-from-CLI.patch
src/patches/stable/0002-Add-include-guards-to-decompiler-C-headers.patch
src/patches/stable/0003-Fix-UBSAN-errors-in-decompiler.patch
src/patches/stable/0004-Use-stroull-instead-of-stroul-to-parse-address-offse.patch
src/patches/stable/0005-Remove-using-namespace-std-from-headers.patch
src/setup-ghidra-source.cmake

Patch to remove 'using namespace std' from headers

---

src/setup-ghidra-source.cmake

Don't merge until we've merged https://github.com/lifting-bits/sleigh/pull/198 and cut a release for 10.3.1.

Update stable to Ghidra v10.3.2

---

.github/workflows/main.yml

macos-latest now points to Apple Silicon macos-14 image, which is causing some tests to fail.

CI: Specifically use macos-12 image

---

.github/workflows/main.yml

macos-latest now points to Apple Silicon macos-14 image, which is causing some tests to fail, and macos-13 is the latest that support x86

CI: Specifically use macos-13 image

---

src/setup-ghidra-source.cmake

Changed files:
```
M       Ghidra/Features/Decompiler/src/decompile/cpp/condexe.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/condexe.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/coreaction.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata_block.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata_op.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/op.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/op.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/ruleaction.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/ruleaction.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/typeop.cc
M …
```

Update Ghidra HEAD to commit ec59e407b

---

src/setup-ghidra-source.cmake

Changed files:
```
M       Ghidra/Features/Decompiler/src/decompile/cpp/fspec.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/fspec.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata_block.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata_op.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/ghidra_translate.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/ghidra_translate.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/marshal.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/modelrules.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/modelrules.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/pcoderaw.cc
M …
```

Bump Ghidra HEAD commit 2ec84c2fb

---

.github/workflows/update_head.yml
scripts/update_ghidra_head.py

Add detailed commit information to the Ghidra HEAD update process:
- Display information about each commit affecting sleigh files
- Include these commit details in GitHub Action PR descriptions
- Add --dry-run flag to preview changes without modifying files
- Improve output formatting and error handling
Also reformat with ruff

Improve Ghidra update process with commit details and dry run mode

---

scripts/update_ghidra_head.py

Can now compare arbitrary commits/tags in Ghidra to collect all changes between versions. This could be used to backfill or create a page with all commit information between official version releases or keep running tabs on changes introduced in HEAD.
Was testing out Cursor and LLM abilities to code this. Seemed to work decently well!

Refactor update ghidra script
