lifting-bits/sleigh

LICENSE, README.md
- Clarify what SLEIGH is and that it is an upstream project not ours
- Disclose that macOS and Windows support is TBD
- Help people find the packages to install the prerequisites/dependencies
- Recommend the --progress flag because otherwise checking out those submodules appears to hang
- Mention what the license on this is
=> Update readme add license

CMakeLists.txt, README.md
This should allow us to do #11.
=> cmake: Remove BFD, Iberty and Zlib dependencies

CMakeLists.txt, tools/sleigh-lift/CMakeLists.txt
Better parallelism and if another project uses this as a submodule, they can just depend on whatever architectures they want.
These commits should be rebased if possible (not squashed).
=> Individual spec compile

.github/workflows/main.yml
Move around where we install dependencies
=> CI: Install updated Linux build tools with Homebrew

CMakeLists.txt, README.md, include/libsleigh.hh, support/CMakeLists.txt, support/SpecFilePaths.h.in, support/Support.cpp, support/Support.cpp.in, support/Support.h, tools/sleigh-lift/CMakeLists.txt, tools/sleigh-lift/src/main.cpp
=> libsleigh: Add helpers for finding spec files

.github/workflows/main.yml
Add documentation building back to CI after #31
=> Build documentation in CI

README.md, tools/sleigh-lift/src/main.cpp
=> sleigh-lift: Add support for loading PSPEC files

CMakeLists.txt
Always make data writes into a CMake target
=> Fix race conditions with CMake copy_directory

.github/workflows/main.yml, CMakeLists.txt, cmake/install-config.cmake
This shouldn't be a breaking change... 🤞 
These commits should be rebased instead of squashed (for readability)
=> Rename CMake exports

cmake/packaging.cmake, src/setup-ghidra-source.cmake
https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.1.2_build
closes #53
=> Update to latest stable 10.1.2 release

.github/workflows/main.yml
This should wait until the following are merged/fixed
closes #54
=> Support for uploading release assets

src/setup-ghidra-source.cmake
=> Shallow clone for stable builds

CMakeLists.txt, support/CMakeLists.txt, tests/find_package/CMakeLists.txt
=> cmake: Build SLEIGH with C++11

.github/workflows/main.yml, src/setup-ghidra-source.cmake, support/CMakeLists.txt
Commits should be rebased onto `master` branch
=> Various improvements

src/setup-ghidra-source.cmake
https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.1.5_build
=> Update to Ghidra stable 10.1.5

.github/workflows/main.yml, tools/sleigh-lift/src/main.cpp
Make real fixes to sleigh-lift for latest commits
=> Fix wrong CMake cache variable in CI

README.md, patches/HEAD/0005-Use-stroull-instead-of-stroul-to-parse-address-offse.patch, patches/stable/0004-Use-stroull-instead-of-stroul-to-parse-address-offse.patch, src/setup-ghidra-source.cmake
=> Add address offset parsing patch

extra-tools/sleigh-lift/src/main.cpp
=> sleigh-lift: Convert address size to bits when calculating bitmask

src/setup-ghidra-source.cmake
This one looks pretty painless. No new source files, no new spec files, patches still apply cleanly, etc.
=> Update stable to Ghidra v10.3.1

src/setup-ghidra-source.cmake
No new source files since the last release so I think this is good to go.
=> Update stable to Ghidra v10.3.3

support/include/sleigh/libsleigh.hh
~Left over from HEAD to stable update~
=> Add note about extra ghidra namespace

src/setup-ghidra-source.cmake
Changed files:
```
M       Ghidra/Features/Decompiler/src/decompile/cpp/fspec.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/modelrules.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/modelrules.hh
M       Ghidra/Processors/TI_MSP430/data/languages/TI_MSP430.cspec
```
=> Bump Ghidra HEAD commit b69e48765

src/setup-ghidra-source.cmake
Changed files:
```
M       Ghidra/Features/Decompiler/src/decompile/cpp/constseq.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/coreaction.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata_op.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata_varnode.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/ruleaction.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/subflow.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/type.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/type.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/varnode.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/varnode.hh
```
=> Bump Ghidra HEAD commit 14527b015

src/setup-ghidra-source.cmake
Changed files:
```
M       Ghidra/Processors/AARCH64/data/languages/AARCH64_golang.register.info
M       Ghidra/Processors/x86/data/languages/x86-64-golang.register.info
```
=> Bump Ghidra HEAD commit 860c75448

src/setup-ghidra-source.cmake
Changed files:
```
M       Ghidra/Processors/Toy/data/languages/toy.sinc
M       Ghidra/Processors/Toy/data/languages/toyInstructions.sinc
```
=> Bump Ghidra HEAD commit cfffcf0c1

src/setup-ghidra-source.cmake
Changed files:
```
M       Ghidra/Features/Decompiler/src/decompile/build.gradle
M       Ghidra/Features/Decompiler/src/decompile/cpp/cast.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/constseq.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/constseq.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/coreaction.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/funcdata_op.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/printc.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/printc.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/printlanguage.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/printlanguage.hh
M …
```
=> Bump Ghidra HEAD commit 213825064

src/setup-ghidra-source.cmake
Changed files:
```
M       Ghidra/Features/Decompiler/src/decompile/cpp/fspec.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/fspec.hh
M       Ghidra/Features/Decompiler/src/decompile/cpp/heritage.cc
M       Ghidra/Features/Decompiler/src/decompile/cpp/modelrules.hh
```
=> Bump Ghidra HEAD commit bb4853e41

src/setup-ghidra-source.cmake
Changed files:
```
M       Ghidra/Features/Decompiler/src/decompile/cpp/heritage.cc
M       Ghidra/Processors/x86/data/languages/avx512.sinc
M       Ghidra/Processors/x86/data/languages/avx512_manual.sinc
```
=> Bump Ghidra HEAD commit 5a3a8c36c

src/patches/stable/0001-Fix-UBSAN-errors-in-decompiler.patch, src/patches/stable/0002-Use-stroull-instead-of-stroul-to-parse-address-offse.patch, src/patches/stable/0003-Use-string-resize-instead-of-reserve.patch, src/patches/stable/0004-Ignore-floating-point-test-due-to-compilation-differ.patch, src/patches/stable/0005-Allow-positive-or-negative-NAN-in-decompiler-floatin.patch, src/patches/stable/0006-decompiler-Fix-strict-weak-ordering-TypePartialEnum.patch, src/patches/stable/0007-Backport-fix-for-datatests-retstruct.xml-tests.patch, src/setup-ghidra-source.cmake
=> Ghidra 11.4
